name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
      - name: Run pytest suite
        run: pytest
      - name: Offline retrieval evaluation
        run: >-
          python scripts/evaluate_retrieval.py
          --dataset Analysis/golden/hybrid_graph_queries.json
          --min-hit-rate 0.9
          --min-mrr 0.8
